### ISSUE TITLE
An error in conversation.py

### ISSUE THREAD

**Issue by Nineves** [radi-cho/datasetGPT#5]
From what I've understood, it should be :
`initial_utterances: List[str] = field(default_factory=lambda: ["Hello."])`
Previously it was:
`initial_utterances: List[str] = "Hello."`

When I was trying to generate conversations with the previous version, I found the model gave me six conversations even when I set num_samples to 1.
Then I discovered that the "initial_utterance" of each conversations turned out to be "H", "e", "l", "l", "o". It does not make sense to let a single letter be the initial utterance of a converstaion.

**Comment by radi-cho** [comment]
Thank you.
